SELECT * FROM AccountantAIO
SELECT * FROM CampaignAccountant
SELECT * FROM CompanyAccountant
SELECT * FROM AnnualBonus
SELECT * FROM Campaign
SELECT * FROM CampaignPlan
SELECT * FROM Client
SELECT * FROM CommunicationPlanner
SELECT * FROM Company
SELECT * FROM Designer
SELECT * FROM EducationLevel
SELECT * FROM Employee
SELECT * FROM PlannerManager
SELECT * FROM Price
SELECT * FROM Traffic
SELECT * FROM TrafficAIO
SELECT * FROM TrafficManager